### ISSUE TITLE
executor_test failing with CUDA build

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/hpx-kokkos#3]
The executor_test fails for me when building hpx-kokkos with CUDA and running ctest. 

To be more specific, the test fails on line https://github.com/STEllAR-GROUP/hpx-kokkos/blob/ce63b0630c739a4df899749ed67baa867862f3fc/tests/executors.cpp#L81 
I've checked, and it is during the tests with the cuda executor (calling the same test method with the default host executor later in the test works fine). From what I can see, the 42 in line https://github.com/STEllAR-GROUP/hpx-kokkos/blob/ce63b0630c739a4df899749ed67baa867862f3fc/tests/executors.cpp#L78 is not copied to the device properly, causing ```passthrough``` in the lambda to be 0 instead of 42 (verified by a ```printf``` inside the lambda).

I quickly tested having a local ```passthrough2 = 42``` variable (declared at the beginning of the test method) which is then captured by the lambda and correctly copied to the device. Using this instead of the argument ```passthrough``` makes the test pass (simply done to verify that this is the only thing going wrong in the test). 

The underlying issue seems to be that the pass-through to the device fails (at least for my build). 

Utilized versions:
- hpx-kokkos master
- HPX 1.6.0
- Kokkos 3.3.01
- nvcc (with gcc 9.3.0 and CUDA 11.2)

**Comment by msimberg** [comment]
@G-071 I finally got to this and I can't reproduce it with 11.0/2 (and gcc 9.3). I am, however, on HPX 1.7.0 and Kokkos develop plus commits to make the HPX backend compile. Were there any other special flags that you used? Did it fail with Release and Debug?

In any case, I'll be preparing PRs for all the changes I have and then you can give it a go to see if it still fails in your environment.

**Comment by msimberg** [comment]
@G-071 do you by any chance have `Kokkos_ENABLE_CUDA_CONSTEXPR=OFF` (it's off by default), or do you not set `--expt-relaxed-constexpr`?

I couldn't reproduce the same error that you had, but I could reproduce an error in that kernel that is supposed to set 42 (the kernel fails and the next `cudaDeviceSynchronize` gives "unspecified launch failure"). This seems to have been fixed by enabling `Kokkos_ENABLE_CUDA_CONSTEXPR`. I suppose in all the builds I've used so far I've automatically just enabled it along with `Kokkos_ENABLE_CUDA_LAMBDA` since the latter was definitely required and I thought I might as well enable both. When setting up CI for HPX-Kokkos I didn't enable it and saw this error.

In #4 I've now added a check to require `CUDA_CONSTEXPR` from Kokkos. If you're interested in trying out the branches it's https://github.com/msimberg/kokkos/tree/hpx-update-deprecations for Kokkos and https://github.com/STEllAR-GROUP/hpx-kokkos/tree/update-hpx-and-kokkos-deps for HPX-Kokkos.

Note that there seems to be a bug in nvcc if you enable `CUDA_CONSTEXPR` *and* use C++17 with CUDA < 11.2: https://github.com/kokkos/kokkos/issues/3496.

**Comment by G-071** [comment]
Yes, I think that was it!

I just tested it with the same build as when opening the issue (so it's not the most recent hpx-kokkos commit anymore), and the executor test fails with ```Kokkos_ENABLE_CUDA_CONSTEXPR=OFF``` and succeeds with ```Kokkos_ENABLE_CUDA_CONSTEXPR=ON``` (I used the default I first encountered this issue which is OFF as you mentioned).
